/**
 * Central icon registry: every lucide icon the app uses is re-exported here
 * so pages/components never import "lucide-react" directly.
 */
export {
  AlertTriangle,
  ArrowLeftRight,
  BarChart3,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Compass,
  CreditCard,
  Download,
  Eye,
  EyeOff,
  FileText,
  Landmark,
  LayoutDashboard,
  LineChart,
  LogOut,
  Mail,
  Moon,
  PiggyBank,
  Plus,
  RefreshCw,
  Repeat,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Sun,
  Target,
  Trash2,
  TrendingUp,
  Upload,
  Wallet,
} from "lucide-react";
