import { beforeEach, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { POST } from "@/app/api/import/preview/route";
import { createImportLayout } from "@/lib/import-profiles";
const state = vi.hoisted(() => ({ enabled: true, from: vi.fn(), serviceFrom: vi.fn() }));
vi.mock("@/lib/feature-flags", () => ({ isFeatureEnabled: () => state.enabled }));
vi.mock("@/lib/http", async importOriginal => ({ ...await importOriginal<object>(), requireUser: async () => ({ user: { id: "owner" }, supabase: { from: state.from } }) }));
vi.mock("@/lib/supabase/service", () => ({ createServiceClient: () => ({ from: state.serviceFrom }) }));
vi.mock("@/lib/rate-limit", () => ({ checkRateLimit: async () => true }));
const text = 'Date,Description,Amount\n31/01/2026,Cafe,-12.50';
const layout = createImportLayout(text, { columns: { date: 0, description: 1, amount: 2, debit: null, credit: null, category: null }, dateOrder: "dmy", positiveIsIncome: true, skipRows: 0 })!;
beforeEach(() => { vi.clearAllMocks(); state.enabled = true; });
it.each([true, false])("stages the reviewed layout snapshot with automatic profile selection %s", async saved => {
  const query = { select: () => query, eq: vi.fn(() => query), limit: async () => ({ data: saved ? [{ id: "profile", name: "Bank", layout }] : [], error: null }), gte: () => query, lte: () => query, order: () => query, range: async () => ({ data: [], error: null }) };
  state.from.mockReturnValue(query);
  const insertBatch = vi.fn(() => ({ select: () => ({ single: async () => ({ data: { id: "batch" }, error: null }) }) }));
  const insertRows = vi.fn((rows: unknown[]) => ({ select: async () => ({ data: rows.map((row, i) => ({ ...(row as object), id: `row-${i}` })), error: null }) }));
  state.serviceFrom.mockImplementation(table => table === "import_review_batches" ? { insert: insertBatch } : { insert: insertRows });
  const form = new FormData(); form.set("file", new File([text], "bank.csv"));
  if (!saved) form.set("date_order", "dmy");
  const response = await POST(new NextRequest("https://example.test/api/import/preview", { method: "POST", body: form }));
  expect(response.status).toBe(200);
  const body = await response.json();
  expect(body).toMatchObject({ batch_id: "batch", can_save_profile: true, applied_profile: saved ? { id: "profile", name: "Bank" } : null, rows: [{ date: "2026-01-31", amount: 12.5, description: "Cafe", flags: [] }] });
  expect(insertBatch).toHaveBeenCalledWith(expect.objectContaining({ user_id: "owner", status: "pending", layout_profile: layout }));
  expect(state.serviceFrom).not.toHaveBeenCalledWith("import_profiles");
  expect(query.eq).toHaveBeenCalledWith("user_id", "owner");
});
